### ISSUE TITLE
Way to get decimals?

### ISSUE THREAD

**Issue by fate8383** [rionshin/HomeKitInfluxGrafana#3]
I am trying to get decimals rather than round it to one's place. Is this possible? I tried removing round from shortcut but it fails. I just cannot figure it out

**Comment by rionshin** [comment]
Hey, I think it is possible. The "issue"   is caused by regional settings on your phone/apple tv, where automation runs - you know some countries use "." some use "," and  when this goes to influxDB it doesn't recognize it.  What i can suggest is to create one automation that insert to InxludDB to a table with no records at all , automation can have only one temp and humidity value(or whatever you want to add) with no  ROUND in it. This way when it insert the records in InfluxDB for 1st time it will create the "column" type correctly - float or text(Based on how your regional settings represent decimal sign) . If your regional represent decimal sign as "." it will add it with no issue, if it is "," then this is TEXT/string/ and when you prepare your  statement it may need to be in quotes " " . You can check influx tutorial on data types : https://docs.influxdata.com/influxdb/v1.8/write_protocols/line_protocol_tutorial/#data-types

**Comment by rionshin** [comment]
By the way if you use Z2M for your Zigbee Temp/Humidity sensors and Switches is much easier. You can use directly Telegraf to consume the data from MQQT and add  it in InfluxDB.

**Comment by fate8383** [comment]
> By the way if you use Z2M for your Zigbee Temp/Humidity sensors and Switches is much easier. You can use directly Telegraf to consume the data from MQQT and add  it in InfluxDB.  

No all zb devices are capable with Prometheus exporter and works great, this is just native HomeKit devices I have few I want to add to the grafana dashboard...

**Comment by fate8383** [comment]
![image](https://user-images.githubusercontent.com/17381874/232349465-041f0dea-11ed-403a-91fc-9acf503f6e65.jpeg)
This way it works. All goes to influx as numbers and accepted, whenever I used "set variable" it cuts of after the dot from HomeKit side so I removed it and also realized no need for it since the variable is already a number.
